import React, { useEffect, useState } from 'react';
import { getHospitalSettings, getInvitations, inviteStaff, updateHospitalSettings } from '../../services/hospitalService';

export default function HospitalSettings() {
  const [settings, setSettings] = useState({ name: '', email: '', paybill: '', brandColor: '#1d427f' });
  const [invite, setInvite] = useState({ name: '', email: '', role: 'DOCTOR' });
  const [invitations, setInvitations] = useState([]);
  const [message, setMessage] = useState('');
  useEffect(() => { getHospitalSettings().then((response) => setSettings(response.data)).catch(() => setMessage('Unable to load hospital settings.')); getInvitations().then((response) => setInvitations(response.data || [])).catch(() => {}); }, []);
  const save = async (event) => { event.preventDefault(); try { await updateHospitalSettings({ paybill: settings.paybill, brandColor: settings.brandColor }); setMessage('Hospital settings saved.'); } catch (error) { setMessage(error.response?.data?.message || 'Unable to save settings.'); } };
  const sendInvite = async (event) => { event.preventDefault(); try { const response = await inviteStaff(invite); setInvitations((items) => [response.data.invitation, ...items]); setInvite({ name: '', email: '', role: 'DOCTOR' }); setMessage('Staff invitation created.'); } catch (error) { setMessage(error.response?.data?.message || 'Unable to create invitation.'); } };
  return <div><div className="admin-dashboard"><h1>{settings.name || 'Hospital'} settings</h1><p>Configure your hospital branding, Paybill, and staff access.</p></div><div className="table-row"><section className="form-card"><h2>Hospital configuration</h2><form onSubmit={save}><input value={settings.name || ''} readOnly placeholder="Hospital name" /><input value={settings.email || ''} readOnly placeholder="Hospital email" /><input value={settings.paybill || ''} onChange={(event) => setSettings({ ...settings, paybill: event.target.value })} placeholder="M-Pesa Paybill number" required /><label>Brand color<input type="color" value={settings.brandColor || '#1d427f'} onChange={(event) => setSettings({ ...settings, brandColor: event.target.value })} /></label><button type="submit">Save hospital settings</button></form></section><section className="form-card"><h2>Invite staff</h2><form onSubmit={sendInvite}><input value={invite.name} onChange={(event) => setInvite({ ...invite, name: event.target.value })} placeholder="Staff full name" required /><input value={invite.email} onChange={(event) => setInvite({ ...invite, email: event.target.value })} type="email" placeholder="Staff email" required /><select value={invite.role} onChange={(event) => setInvite({ ...invite, role: event.target.value })}><option>DOCTOR</option><option>NURSE</option><option>PHARMACIST</option><option>RECEPTIONIST</option><option>CASHIER</option></select><button type="submit">Create invitation</button></form><h3>Recent invitations</h3>{invitations.map((item) => <p key={item.id}>{item.name} · {item.role} · {item.status}</p>)}</section></div>{message && <div className="panel-note">{message}</div>}</div>;
}
